
services:
  postgres:
    image: postgres:latest  # <-- CORRIGIDO
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "9001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9000:80"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pgdata: